repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pytest-platform-agnostic
        name: pytest
        entry: python -c "import os, sys, platform; sys.path.insert(0, os.getcwd()); cmd = 'uv run pytest tests/ -v'; os.system(cmd)"
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        verbose: true
        env:
          - VIRTUAL_ENV: .venv
