name: Duplicate Issue Detection
on:
  issues:
    types: [opened]

jobs:
  detect-duplicates:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # This composite action sets PYTHONPATH to include the workspace directory
      # See .github/actions/set-pythonpath/action.yml for details
      - name: Set PYTHONPATH
        uses: ./.github/actions/set-pythonpath

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub scikit-learn

      - name: Analyze Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: "1"
        run: |
          python -u .github/scripts/identify_duplicates.py
