name: Comment on New Issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run duplicate issue checker
      run: python scripts/identify_duplicates.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
