name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"

    - name: Verify test discovery
      run: |
        pytest tests/unit/ --collect-only --continue-on-collection-errors

    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=my_chat_gpt_utils --cov-report=xml --cov-report=html --continue-on-collection-errors

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"

    - name: Verify test discovery
      run: |
        pytest tests/integration/ --collect-only --continue-on-collection-errors

    - name: Run integration tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest tests/integration/ -v --cov=my_chat_gpt_utils --cov-report=xml --cov-report=html --continue-on-collection-errors
